Added helper functions (see #137)
ramnes/notion-sdk-py pull request #148
Opened 2022-09-14 13:23 UTC by mutt0-ds

Hello! I've worked on the issue #137 and added the helper functions following the same structure of notion-sdk-js.

I have a couple of doubts about the typing in the Async version, since I'm rarely working with this kind of functions, so please let me know if it's ok.

I tested them locally with my Notion. but I couldn't add tests because they require a mock call to the API... Should we raise an issue and work on it?

We also need to update the README, I'll do it if the request is approved

2022-09-14 18:24 UTC, ramnes requested changes
LGTM overall, just a few little things to change

2022-09-14 18:24 UTC, ramnes commented on notion_client/helpers.py
> +    function: Callable[..., Any], first_page_args: Dict[Any, Any]
Let's use kwargs?

```suggestion
    function: Callable[..., Any], **kwargs: Any
```

2022-09-14 18:24 UTC, ramnes commented on notion_client/helpers.py
> +def iterate_paginated_API(
IIRC Python functions must always be lowercase

```suggestion
def iterate_paginated_api(
```

2022-09-14 18:24 UTC, ramnes commented on notion_client/helpers.py
> +        if (not response["has_more"]) | (next_cursor is None):
```suggestion
        if not response.get("has_more") or not next_cursor:
```

2022-09-14 18:27 UTC, ramnes commented
Thank you very much for taking this work!

I would love if the README changes could be added to the same commit as well. :)

For the tests, it's true that cassettes are great for me as a sole-developer but not practical at all for collaboration. Do you have any idea on how we could do things differently? c.f. https://github.com/ramnes/notion-sdk-py/pull/116#issuecomment-1101463557

2022-09-14 21:47 UTC, mutt0-ds commented
I'll work on the README tomorrow, while I'm thinking about an easy way for handling tests. We can mockup all the responses or maybe use a secret token associated to the notion example at [test_helpers](https://github.com/ramnes/notion-sdk-py/blob/main/tests/test_helpers.py)?

2022-09-15 10:32 UTC, ramnes commented
I think the key is to not rely on existing pages or other data we can't control. We should just give the tests a private token and a root page, and then they'd bootstrap a test environment (i.e. a few pages) within the given root page.

That way, anyone could run the tests with their own Notion account. We could still use the cassettes to speed up most tests, but that wouldn't be a blocker anymore to add more tests.

2022-09-15 10:34 UTC, ramnes commented on notion_client/helpers.py
> +def iterate_paginated_API(
Did you resolve it but forgot to include the changes in the commit? :sweat_smile:

2022-09-15 14:17 UTC, evertheylen commented on notion_client/helpers.py
> +        response = function(kwargs, start_cursor=next_cursor)
Is this not supposed to be `**kwargs`? Awaiting the merge of this PR, I copied the code but I had to change this to make it work.

2022-09-15 20:54 UTC, mutt0-ds commented
@ramnes OK about tests, I agree. 
I'll think about the setup in the next days (and probably open a new issue or referring to the existing one about coverage). Thanks!

2022-09-20 12:57 UTC, davideph commented
> LGTM overall, just a few little things to change

Changes done!

2022-09-20 13:34 UTC, ramnes commented on notion_client/helpers.py
> +        if (not response["has_more"]) | (next_cursor is None):
Did you forget to commit these changes?

2022-09-20 13:36 UTC, ramnes commented
One little thing left :)

2022-09-21 10:11 UTC, merged

2022-09-21 10:11 UTC, ramnes commented
Thanks! 🚀