Add url helpers
ramnes/notion-sdk-py pull request #40
Opened 2021-05-25 04:50 UTC by aahnik

It's a very common requirement to access a page by its URL.  We could definitely do a search, but multiple pages/databases may exist with the same name.

When a python application reads/writes to a Notion page or database, fetching the exact object is required. The user could easily share the URL with the application, and the app can determine the id from the URL. With the id, the developer can retrieve the exact object.

- I have added helper functions to get the id from the URL or get the URL from the id.
- I have added `tests` for these functions. As nothing happens over the network, we don't need trio for this
- I have added `helpers` to the reference section of the docs site.

2021-05-25 08:03 UTC, ramnes requested changes

2021-05-25 08:03 UTC, ramnes commented on notion_client/helpers.py
> +    return "-".join([slug[0:8], slug[8:12], slug[12:16], slug[16:20], slug[20:32]])
This is really flimsy and based on a lot of expectations that could be wrong. Try to see the output of something like `notion.so/123`. It should not return something broken but rather None, or raise an error. You probably want to use `urllib.parse` here. :)

2021-05-25 08:03 UTC, ramnes commented on tests/test_helpers.py
> +    }
I don't see a reason to build a list and unpack it at the same time here:

```suggestion
    assert pick(my_dict, "Product") == {"Product": "Notion"}
    assert pick(my_dict, "API", "python-sdk") == {
        "API": 2021,
        "python-sdk": "ramnes",
    }
```

2021-05-27 10:12 UTC, aahnik commented on notion_client/helpers.py
> +    return "-".join([slug[0:8], slug[8:12], slug[12:16], slug[16:20], slug[20:32]])
Sure, I will do so. I will also add test cases, to check if the function is raising proper errors when a wrong URL is given.

2021-05-28 05:58 UTC, aahnik reviewed
I have used `urlib.parse` It's fantastic, as it does all URL-related validation.

and `UUID` does all validation regarding the 32 characters long hex string.

the dash and non-dash format conversion is also handled by that.

2021-05-28 05:59 UTC, aahnik reviewed
i re-checked all changes to make sure nothing breaks!

2021-05-28 22:17 UTC, merged

2021-05-28 22:17 UTC, ramnes commented
Thanks!